"""initial_schema

Revision ID: aea756041e7c
Revises:
Create Date: 2026-04-08 12:47:06.054029
"""

import os
import re
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aea756041e7c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None
APP_DB_ROLE = os.getenv("INTERVIEW_ENGINE_APP_ROLE", "talentscout_app")

if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", APP_DB_ROLE):
    raise ValueError("INTERVIEW_ENGINE_APP_ROLE must be a valid postgres identifier")


def upgrade() -> None:
    # JSONB fields remain schemaless at the database layer. Their shape is validated and
    # evolved in the Pydantic layer; Alembic autogenerate will not detect JSONB schema
    # changes. Document every version in docs/jsonb_schemas.md and backfill with
    # scripts/migrate_jsonb_<field>_<version>.py when the application schema changes.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interview_sessions",
        sa.Column("candidate_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recruiter_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("candidate_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("candidate_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("livekit_room_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("langgraph_thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED", "IN_PROGRESS", "COMPLETED", "ABANDONED", "ERROR", name="sessionstatus"
            ),
            nullable=False,
        ),
        sa.Column("current_round", sa.Integer(), nullable=False),
        sa.Column("screening_score", sa.Float(), nullable=False),
        sa.Column("assessment_score", sa.Float(), nullable=False),
        sa.Column("assessment_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weak_areas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extracted_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("speech_score", sa.Float(), nullable=True),
        sa.Column("integrity_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("transcript", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("livekit_room_name"),
    )
    op.create_index(
        op.f("ix_interview_sessions_candidate_id"),
        "interview_sessions",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_job_id"), "interview_sessions", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_sessions_langgraph_thread_id"),
        "interview_sessions",
        ["langgraph_thread_id"],
        unique=False,
    )
    op.create_table(
        "parsed_job_contexts",
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("seniority", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("must_have_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("question_seed_topics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requires_coding", sa.Boolean(), nullable=False),
        sa.Column("linting_warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parsed_job_contexts_job_id"), "parsed_job_contexts", ["job_id"], unique=True
    )
    op.create_table(
        "interview_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dimension_targeted", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_messages_session_id"), "interview_messages", ["session_id"], unique=False
    )
    op.create_table(
        "scorecards",
        sa.Column("candidate_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("final_rank", sa.Integer(), nullable=True),
        sa.Column("weighted_total", sa.Float(), nullable=False),
        sa.Column(
            "interview_dimension_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("assessment_score", sa.Float(), nullable=False),
        sa.Column("speech_score", sa.Float(), nullable=True),
        sa.Column("screening_score", sa.Float(), nullable=False),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "recommended_action",
            sa.Enum("ADVANCE", "HOLD", "REJECT", name="recommendedaction"),
            nullable=False,
        ),
        sa.Column("integrity_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("bias_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("judge_ensemble_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recruiter_overrides", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_finalized", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scorecards_candidate_id"), "scorecards", ["candidate_id"], unique=False
    )
    op.create_index(op.f("ix_scorecards_job_id"), "scorecards", ["job_id"], unique=False)
    op.create_index(op.f("ix_scorecards_session_id"), "scorecards", ["session_id"], unique=True)
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_DB_ROLE}') THEN
                    EXECUTE 'GRANT INSERT ON audit_logs TO "{APP_DB_ROLE}"';
                    EXECUTE 'REVOKE UPDATE, DELETE ON audit_logs FROM "{APP_DB_ROLE}"';
                END IF;
            END
            $$;
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scorecards_session_id"), table_name="scorecards")
    op.drop_index(op.f("ix_scorecards_job_id"), table_name="scorecards")
    op.drop_index(op.f("ix_scorecards_candidate_id"), table_name="scorecards")
    op.drop_table("scorecards")
    op.drop_index(op.f("ix_interview_messages_session_id"), table_name="interview_messages")
    op.drop_table("interview_messages")
    op.drop_index(op.f("ix_parsed_job_contexts_job_id"), table_name="parsed_job_contexts")
    op.drop_table("parsed_job_contexts")
    op.drop_index(
        op.f("ix_interview_sessions_langgraph_thread_id"), table_name="interview_sessions"
    )
    op.drop_index(op.f("ix_interview_sessions_job_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_candidate_id"), table_name="interview_sessions")
    op.drop_table("interview_sessions")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
